### PR TITLE
Update constants.py

### PR DESCRIPTION
**Pull request by mvdroest**
Add support for the 256 FFT size

### CODE REVIEW

**Comment by EarToEarOak** [comment]
No idea how I managed to miss that one! Thank you.

**Comment by mvdroest** [comment]
Welcome Al.

Happu to help you.

Btw can you already send me some sources of the power program? I can then
see what is missing, code it and send it back for you approval ;)

**Comment by EarToEarOak** [comment]
Hi,
I'm not sure which sources you need, everything should be available in this repository.

**Comment by mvdroest** [comment]
Hi Al,

For the nice Power program you are building for Stefan Immerzeel of the
LVNL ;) I can help him then for his thesis and also contribute more back to
you.
Its the power output program where you measure the DB level of a frequancy.

**Comment by EarToEarOak** [comment]
I see, you can find the program in this [repository](https://github.com/EarToEarOak/RF-Monitor), look at 'receive.py' at line 64.
I've used the [psd()](http://matplotlib.org/api/mlab_api.html#matplotlib.mlab.psd) function from matplotlib

**Pull request merged**
