### PR TITLE
Modularized and added support for setuptools

### PR DESCRIPTION
**Pull request by yarda**
This is my attempt to modularize the code and add support for setuptools. This ease downstream distro packaging. I tried to sanely set 'setup.py' metadata, but it may still need  some improvements. I also changed all local imports to relative path, because recently there was opened downstream Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1383513 regarding conflicting name with the Event package. While I have been trying to fix this bug, I have decided to also fix the modularization.

### CODE REVIEW

**Comment by yarda** [comment]
Also added src/version.py to track the package version on one place.

**Comment by EarToEarOak** [comment]
Thanks,
I have no experience of setuptools and was wondering if it's possible to do this without moving `rtlsdr_scan.py` to the `bin` directory?  This will break the Windows installer and will also confuse users who are used to running it from the `src` directory.

**Comment by yarda** [comment]
I will check the possibility.  The standard way is to provide the standalones in so called scripts directory, but hopefully I will come with some compatible solution.

**Comment by yarda** [comment]
Yup, it seems to work, I will update the patch. One question: could the main executable file be named 'rtlsdr_scan', i.e. without the '.py' suffix? But no problem for me to rename it in the downstream install script.

**Comment by EarToEarOak** [comment]
Great.
For the moment I'd prefer to keep the '.py' extension to reduce confusion, but I see the advantage to removing it.

**Comment by yarda** [comment]
No problem, push forced the new patch which keeps the suffix, I will rename it downstream. Also feel free to update the setup, currently it doesn't handle the resources, but I think it's minor problem at the moment.

**Comment by yarda** [comment]
Yes, I side-install it downstream. But I think it could be also done by setuptools. In such case you could simply run:
python setup.py build && python setup.py install

And all would be setup no matter of the platform / OS used.

Currently I do:
python setup.py build && python setup.py install && cp -r res TARGETDIR

But I think this is minor, we could extend the setup.py later. I am not expert of setuptools, but I think it should be possible.

**Comment by EarToEarOak** [comment]
I think it's preferable to have setuptools do all the installing, rather than manually copying the resources.  It would also mean the egg file would include these files for distribution.

**Comment by EarToEarOak** [comment]
I've had a quick play with including the resource files.  Looks like the directory structure needs to be made more package-like; renaming `src` to `rtlsdr-scanner` and moving `res` into this.

The functions which load the resources will then need to check if setuptools was used and then load them as described [here](https://setuptools.readthedocs.io/en/latest/setuptools.html#id16).

**Comment by EarToEarOak** [comment]
I've added setuptools support in 9db6892ab7742f46ba37e9e18cfd4f810d9b9f46 (and a few bug squashes after that).  I've also uploaded the package to [PyPi](https://pypi.python.org/pypi/rtlsdr_scanner/1.1.1).

As I suspected they key was to turn it into a proper Python package, the rest came fairly easily after that. 

As the events.py is a sub-module of rtlsdr-scanner it no longer seems to (or should) cause the Fedora import error.

Although I didn't merge your pull I found your modifications to be useful and have to thank you for all your help.

**Comment by yarda** [comment]
OK, thanks for info, I will update the package in Fedora, so closing the pull request.

**Pull request closed without merging**
